### ISSUE TITLE
conda Windows build

### ISSUE THREAD

**Issue by richardjgowers** [greglandrum/yaehmop#21] opened 2018-12-13 22:42 UTC
edit:

conda-forge package is live, but it doesn't have a windows build currently.  Can be by including a build.bat in the recipe.

-------
Hello

I'm using yaehmop in a package I'm developing, it would be great if there was a conda-forge package for this, so I'm going to put together one... Unless there's already something existing I've missed?

For this it would be easier if this repo used tags to denote versions of the program.  Then a new build could be triggered when a new tag is uploaded (ie not for every commit).

**Comment by richardjgowers** [comment] 2018-12-28 17:00
https://github.com/conda-forge/staged-recipes/pull/7419

@greglandrum I've started the conda package there, if you want I can add you as a maintainer too

**Comment by richardjgowers** [comment] 2018-12-28 20:19
@greglandrum also can you push a tag to github & create a release on github so I've got something static to target for the conda build? Thanks

**Comment by richardjgowers** [comment] 2018-12-30 17:53
@greglandrum the conda package for tightbind is working now (Linux & Macos, not yet on windows, possible with demand though), the only thing holding it up is the lack of git tag & release to point to from conda forge.  Then making a new release is as easy as pushing a new tag to github, where conda forge will see that and mint a new release automagically

I did have to change the binary name of 'bind' to 'yaehmop' - bind is already taken and is a bit generic.

Once #23 gets done we can also add the libyaehmop stuff into the conda packaging so integration with rdkit can use the conda package too

**Comment by greglandrum** [comment] 2019-01-01 07:19
@richardjgowers: Here's the tag/release: https://github.com/greglandrum/yaehmop/releases/tag/v2018.12.1

**Comment by greglandrum** [comment] 2019-01-01 07:21
On renaming: I agree that "bind" isn't the best name ever. yaehmop is a bit broad for just the executable that does the eHT calculation though... how about calling the executable `eht_bind` instead?

**Comment by thegodone** [comment] 2019-01-10 13:16
eht_calc ?

**Comment by greglandrum** [comment] 2019-01-10 15:45
that would work for me

**Comment by richardjgowers** [comment] 2019-01-11 17:24
Ok the conda-forge package is live, except for Windows.  It should auto update whenever new release tags are pushed to this repo.

@thegodone I used the suggestion of `eht_bind` in the end, I can change this if it's a real problem?

**Comment by thegodone** [comment] 2019-01-11 19:10
No prob, one of my colleague is working on integration into rdkit. We should discuss next week if we have progress on our side on that secondary topic.

Envoyé de mon iPhone

**Comment by ghutchis** [comment] 2022-07-13 15:51
@richardjgowers - I'd love to see a Windows build. Since I'm not super-conversant in `conda-forge` what would be needed to try that out? I guess I'd need to fork `yaehmop-feedstock` and try adding in a `build.bat` script?

**Comment by richardjgowers** [comment] 2022-07-13 16:06
@ghutchis yes as a first step, then we can see what errors spring out. I think there'll also be a line or two in the meta.yaml which currently disable the windows build.

**Comment by ghutchis** [comment] 2022-07-13 19:20
Okay, I added an `osx_arm64` build on `yaehmop-feedstock` and I'll sort out a Windows build next.

**Comment by richardjgowers** [comment] 2022-07-22 11:19
@ghutchis if you can check that this works in Windows now we can close this

**Comment by greglandrum** [comment] 2022-07-22 12:30
@richardjgowers I installed this in a conda env on windows and confirmed that it works (and produces correct results) on one of the yaehmop example inputs.

**Comment by ghutchis** [comment] 2023-05-01 17:08
Bump - if the Windows build works, can we close this issue?

**Closed as completed** 2024-04-08 11:01 UTC
